
--IKEA Furniture Retails Sales Data Management
--Viewing the structure of the Table "Sales Project" :

select * from salesproject;

--(1)-Query for calculating Total Revenue generated Year wise ?

select year(order_date) as Year, round(sum(total_sales),2) as Total_Revenue from SalesProject
group by Year(Order_Date)
order by Sum(total_sales);

--(2)-Query for calculating the most amount of Revenues generated by which region ?

select Region,sum(total_sales) as Total_Revenue from salesproject
group by region
order by sum(total_sales);

--(3)-Query for checking the count of Ship_Mode Region wise ?

select distinct(Region), count(Ship_Mode) as Count from salesproject
group by Region
order by count(Ship_Mode);

--(4)-Query for calculating total sales generated by various ship mode types ?

select distinct(ship_mode), Round(sum(total_sales),2) as Total_Sales from SalesProject
group by Ship_Mode
order by Total_Sales;

--(5)-Query for selecting cities with most ordered Unit in all Sub-Categories ?

select city, count(units) as Most_Ordered from SalesProject
group by City
order by count(units) desc;


--(6)-Query for Checking cities generating maximum revenue ?

Select city, sum(total_sales) as Max_Revenue from SalesProject
group by city 
order by sum(total_sales) desc;


--(7)-Query for calculating the most order and most sales sub-categories ?

select distinct(sub_category), count(units) as Most_Ordered, sum(total_sales) as Most_Sales from SalesProject
group by Sub_Category
order by count(units) desc, sum(total_sales) desc;

--(8)-Query for checking the majority segment (sales wise) present in all the regions ?

select distinct(segment),Round(sum(total_sales),2) as Max_Revenue from SalesProject
group by Segment
order by Max_Revenue desc; 

--(9)-Query for checking the Major Category Product leading the market all time ?

select distinct(category),Round(sum(total_sales),2) as Market_Lead from SalesProject
group by Category
order by Market_Lead desc;

--(10)-Query to check in which State the market sales is more dense ?

select distinct(state), year(order_date) as Year_wise,sum(total_sales) as Mar_Lead from SalesProject
group by state, year(order_date)
order by Mar_Lead desc;

--(11)-Query to check increase in shipping mode year wise ?

select distinct(ship_mode), year(order_date) as Year_Wise, count(ship_mode) over (partition by year(order_date)) as total from SalesProject
group by Order_Date,Ship_Mode
order by (Ship_Mode);
